---
- name: Deploy Backend
  hosts: all
  tasks:
    - name: Start minikube service
      service:
        name: minikube
        state: started
    - name: apply configmap
      shell: kubectl apply -f mysql-configmap.yaml
    - name: apply secrets
      shell: kubectl apply -f mysql-secrets.yaml
    - name: apply mysql
      shell: kubectl apply -f mysql-deployment.yaml
    - name: apply app
      shell: kubectl apply -f app-deployment.yaml